# Generated by Django 5.2.12 on 2026-06-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('categoria', models.CharField(choices=[('carnes', 'Carnes'), ('hortifruti', 'Hortifrúti'), ('laticinios', 'Laticínios'), ('graos_cereais', 'Grãos e Cereais'), ('temperos', 'Temperos e Condimentos'), ('bebidas', 'Bebidas'), ('padaria', 'Padaria'), ('enlatados', 'Enlatados e Conservas'), ('congelados', 'Congelados'), ('doces', 'Doces e Sobremesas'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='quantidade')),
                ('unidade', models.CharField(blank=True, default='', max_length=30, verbose_name='unidade')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_ingrediente', to='recipes.ingrediente', verbose_name='ingrediente')),
            ],
            options={
                'verbose_name': 'ingrediente da receita',
                'verbose_name_plural': 'ingredientes da receita',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descricao')),
                ('modo_preparo', models.TextField(blank=True, default='', verbose_name='modo de preparo')),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='facil', max_length=10, verbose_name='dificuldade')),
                ('tempo_preparo', models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo de preparo (min)')),
                ('porcoes', models.PositiveIntegerField(blank=True, null=True, verbose_name='porcoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='groups.grupo', verbose_name='grupo')),
                ('ingredientes', models.ManyToManyField(related_name='receitas', through='recipes.IngredienteReceita', to='recipes.ingrediente', verbose_name='ingredientes')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ingredientereceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_receita', to='recipes.receita', verbose_name='receita'),
        ),
        migrations.CreateModel(
            name='CompartilhamentoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compartilhamento', models.DateTimeField(auto_now_add=True, verbose_name='data de compartilhamento')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_compartilhadas', to='groups.grupo', verbose_name='grupo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='recipes.receita', verbose_name='receita')),
            ],
            options={
                'verbose_name': 'compartilhamento de receita',
                'verbose_name_plural': 'compartilhamentos de receita',
            },
        ),
        migrations.AddConstraint(
            model_name='ingredientereceita',
            constraint=models.UniqueConstraint(fields=('receita', 'ingrediente'), name='unique_receita_ingrediente'),
        ),
        migrations.AddConstraint(
            model_name='compartilhamentoreceita',
            constraint=models.UniqueConstraint(fields=('receita', 'grupo'), name='unique_compartilhamento_receita_grupo'),
        ),
    ]
