# Generated by Django 5.2.12 on 2026-06-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrupoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('dono', 'Dono'), ('membro', 'Membro')], default='membro', max_length=10, verbose_name='papel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='groups.grupo', verbose_name='grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_grupo', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membro do grupo',
                'verbose_name_plural': 'membros do grupo',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'grupo'), name='unique_usuario_grupo')],
            },
        ),
    ]
