# Generated by Django 5.2.12 on 2026-06-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('planning', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compra', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_compra', to='groups.grupo', verbose_name='grupo')),
                ('plano_semanal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_compra', to='planning.planosemanal', verbose_name='plano semanal')),
            ],
            options={
                'verbose_name': 'lista de compras',
                'verbose_name_plural': 'listas de compras',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_manual', models.CharField(blank=True, default='', help_text='Nome para itens avulsos (sem vinculo a ingrediente).', max_length=200, verbose_name='nome manual')),
                ('quantidade', models.FloatField(default=1.0, verbose_name='quantidade')),
                ('unidade', models.CharField(blank=True, default='', max_length=30, verbose_name='unidade')),
                ('comprado', models.BooleanField(default=False, verbose_name='comprado')),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_compra', to='recipes.ingrediente', verbose_name='ingrediente')),
                ('lista_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='shopping.listacompra', verbose_name='lista de compras')),
            ],
            options={
                'verbose_name': 'item de compra',
                'verbose_name_plural': 'itens de compra',
                'ordering': ['comprado', 'id'],
            },
        ),
    ]
