# Generated by Django 5.2.12 on 2026-06-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_referencia', models.DateField(help_text='Data da segunda-feira da semana.', verbose_name='semana de referencia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_semanais', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_semanais', to='groups.grupo', verbose_name='grupo')),
            ],
            options={
                'verbose_name': 'plano semanal',
                'verbose_name_plural': 'planos semanais',
                'ordering': ['-semana_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='dia da semana')),
                ('tipo_refeicao', models.CharField(choices=[('cafe', 'Café da Manhã'), ('almoco', 'Almoço'), ('lanche', 'Lanche'), ('jantar', 'Jantar'), ('ceia', 'Ceia')], max_length=10, verbose_name='tipo de refeicao')),
                ('plano_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='planning.planosemanal', verbose_name='plano semanal')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='recipes.receita', verbose_name='receita')),
            ],
            options={
                'verbose_name': 'refeicao',
                'verbose_name_plural': 'refeicoes',
            },
        ),
        migrations.AddConstraint(
            model_name='planosemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('grupo__isnull', True)), fields=('criador', 'semana_referencia'), name='unique_plano_pessoal_por_semana'),
        ),
        migrations.AddConstraint(
            model_name='planosemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('grupo__isnull', False)), fields=('grupo', 'semana_referencia'), name='unique_plano_grupo_por_semana'),
        ),
        migrations.AddConstraint(
            model_name='refeicao',
            constraint=models.UniqueConstraint(fields=('plano_semanal', 'dia_da_semana', 'tipo_refeicao', 'receita'), name='unique_refeicao_slot_receita'),
        ),
    ]
